mysql:
  use-mysql: true
  host: 163.123.183.87
  port: 31372
  database: Items
  username: admin
  password: mTf1TEmT
Redis:
  use-redis: true
  redishost: 'localhost'
  redispass: ''
  redisport: 6379